/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.unibas.ias.webcrawler;

import ch.unibas.ias.webcrawler.webcrawler.WebCrawler;

public class App {

    public static void main(String[] args) throws Exception {

        WebCrawler.main(args);

    }
}
